name: py39

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.9
  - astropy=5.3.4
  - numpy
  - pandas
  - poliastro
  - jupyter
  - ipykernel
  - nbconvert
  - pip
  - pip:
    - sparqlwrapper
    - rpy2 
    - nbconvert

  