PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:        <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX project:        <http://imce.jpl.nasa.gov/foundation/project#>
PREFIX analysis:        <http://imce.jpl.nasa.gov/foundation/analysis#>

SELECT DISTINCT ?iri ?source ?nodetype
WHERE {
  {
    {
      {
        VALUES ?concept { project:WorkPackage }
        VALUES ?relation { project:executes }
        ?parentiri a ?concept .
        ?parentiri ?relation ?iri .

        VALUES ?filter_iri { "http://example.com/model/description/analysis/orbit_analysis_02#cdp-analysis-02" }
        FILTER(STRSTARTS(STR(?parentiri), ?filter_iri)) .

        ?iri project:interchangesThrough ?ip_iri.
        ?ip_iri project:delivers ?targetIri.

        BIND(STRAFTER(STR(?iri), "#") AS ?source) .
       BIND("Subsystem" AS ?nodetype).
     }
      UNION
      {
        VALUES ?concept { project:WorkPackage }
        VALUES ?relation { project:executes }
        ?parentiri a ?concept .
        ?parentiri ?relation ?iri .

        VALUES ?filter_iri { "http://example.com/model/description/analysis/orbit_analysis_02#cdp-analysis-02" }
        FILTER(STRSTARTS(STR(?parentiri), ?filter_iri)) .

        ?iri project:interchangesThrough ?ip_iri.
        ?ip_iri project:receives ?targetIri.

        BIND(STRAFTER(STR(?iri), "#") AS ?source) .
        BIND("Subsystem" AS ?nodetype).
     }
    }
    UNION
    {
      {
        VALUES ?concept { project:WorkPackage }
        VALUES ?relation { project:executes }
        ?parentiri a ?concept .
        ?parentiri ?relation ?sourceIri .

        VALUES ?filter_iri { "http://example.com/model/description/analysis/orbit_analysis_02#cdp-analysis-02" }
        FILTER(STRSTARTS(STR(?parentiri), ?filter_iri)) .

        ?sourceIri project:interchangesThrough ?ip_iri.
        ?ip_iri project:delivers ?iri.

        BIND(STRAFTER(STR(?iri), "#") AS ?source) .
        BIND("Assembly" AS ?nodetype).
      }
      UNION
      {
        VALUES ?concept { project:WorkPackage }
        VALUES ?relation { project:executes }
        ?parentiri a ?concept .
        ?parentiri ?relation ?sourceIri .

        VALUES ?filter_iri { "http://example.com/model/description/analysis/orbit_analysis_02#cdp-analysis-02" }
        FILTER(STRSTARTS(STR(?parentiri), ?filter_iri)) .

        ?sourceIri project:interchangesThrough ?ip_iri.
        ?ip_iri project:receives ?iri.

        BIND(STRAFTER(STR(?iri), "#") AS ?source) .
        BIND("Assembly" AS ?nodetype).
      }
    }
  }
  UNION
  {
    VALUES ?componentType { project:WorkPackage }
    VALUES ?relationType { project:executes }
    VALUES ?filter_iri { "http://example.com/model/description/analysis/orbit_analysis_02#cdp-analysis-02" "http://example.com/model/description/cdpworkflow"}
    FILTER(STRSTARTS(STR(?iri), ?filter_iri)) .  

    {
      ?iri a ?componentType ;
      OPTIONAL{
        ?iri ?relationType ?targetIri ;
      }
      BIND(STRAFTER(STR(?iri), "#") AS ?source) .
       BIND("System" AS ?nodetype).
    }
    UNION
    {
   		?sourceIri a ?componentType ;

      OPTIONAL{
        ?sourceIri ?relationType ?iri ;
      }
      BIND(STRAFTER(STR(?iri), "#") AS ?source) .  
       BIND("Subsystem" AS ?nodetype).
    }
  }
}
ORDER BY ?targetIri