name: CI

on:
  push:
    branches: [ "experiment2" ]
  pull_request:
    branches: [ "experiment2" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Check Current Locale
      run: Get-WinSystemLocale
      shell: pwsh

    - name: Set Japanese
      run: Set-WinSystemLocale ja-JP
      shell: pwsh

    - name: Check Current Locale
      run: Get-WinSystemLocale
      shell: pwsh
