name: CI

on:
  push:
    branches: [ "experiment2" ]
  pull_request:
    branches: [ "experiment2" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build
      run: ./gradlew build -d

    - name: Publish Docs
      uses: actions/upload-pages-artifact@v1
      with:
        path: build/owl