name: CI

on:
  push:
    branches: [ "experiment2" ]
  pull_request:
    branches: [ "experiment2" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Check Current Locale
      run: Get-WinSystemLocale
      shell: pwsh

    - name: Install Japanese Language Pack
      run: |
        Set-Culture ja-JP
        Set-WinSystemLocale -SystemLocale ja-JP
        Set-WinUILanguageOverride -Language ja-JP
        Set-WinUserLanguageList ja-JP -Force
        Set-WinHomeLocation -GeoId 94
      shell: pwsh

    - name: Reboot to Apply Changes (if necessary)
      run: shutdown -r;exit
      shell: cmd

