name: CI

on:
  push:
    branches: [ "experiment2" ]
  pull_request:
    branches: [ "experiment2" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Check Current Locale
      run: Get-WinSystemLocale
      shell: pwsh

    - name: Install Japanese Language Pack
      shell: pwsh
      run: |
        # Install Japanese language pack
        Add-WindowsCapability -Online -Name "Language.Basic~~~ja-JP~0.0.1.0"
        Add-WindowsCapability -Online -Name "Language.Handwriting~~~ja-JP~0.0.1.0"
        Add-WindowsCapability -Online -Name "Language.OCR~~~ja-JP~0.0.1.0"
        Add-WindowsCapability -Online -Name "Language.Speech~~~ja-JP~0.0.1.0"
        Add-WindowsCapability -Online -Name "Language.TextToSpeech~~~ja-JP~0.0.1.0"

        # Set Japanese as the default system locale
        Set-WinSystemLocale -SystemLocale ja-JP

        # Set Japanese as the default user locale
        $LangList = Get-WinUserLanguageList
        $LangList.Add("ja-JP")
        Set-WinUserLanguageList -LanguageList $LangList -Force

    - name: Install Japanese Language Pack
      shell: pwsh
      run: |
        Restart-Computer -Force

    - name: Check Current Locale
      run: Get-WinSystemLocale
      shell: pwsh
  